version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - gocritic
    - misspell
    - prealloc
    - revive
    - unconvert
  settings:
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: internal/http/interceptors/log/log.go
        text: 'SA1019:'
      - linters:
          - staticcheck
        path: pkg/utils/utils.go
        text: 'SA1019:'
      - linters:
          - scopelint
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
