with-expecter: true
filename: "{{.InterfaceName }}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/opencloud-eu/reva/v2/pkg/publicshare/manager/owncloudsql:
        interfaces:
            UserConverter:
    github.com/opencloud-eu/reva/v2/pkg/publicshare:
        interfaces:
            Manager:
    github.com/opencloud-eu/reva/v2/pkg/share:
        interfaces:
            Manager:
    github.com/opencloud-eu/reva/v2/pkg/share/manager/owncloudsql:
        interfaces:
            UserConverter:
    github.com/opencloud-eu/reva/v2/pkg/storage/pkg/decomposedfs/permissions:
        interfaces:
            PermissionsChecker:
            CS3PermissionsClient:
    github.com/opencloud-eu/reva/v2/pkg/storage/pkg/decomposedfs/node:
        interfaces:
            Blobstore:
    github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/lookup:
        interfaces:
            IDCache:
    github.com/opencloud-eu/reva/v2/pkg/storage/registry/spaces:
        interfaces:
            StorageProviderClient:
    github.com/opencloud-eu/reva/v2/pkg/storage/utils/decomposedfs/permissions:
        interfaces:
            PermissionsChecker:
            CS3PermissionsClient:
    github.com/opencloud-eu/reva/v2/pkg/storage/utils/decomposedfs/tree:
        interfaces:
            Blobstore:
    github.com/opencloud-eu/reva/v2/pkg/storage/utils/metadata:
        interfaces:
            Storage:
    github.com/opencloud-eu/reva/v2/tests/cs3mocks:
        interfaces:
            GatewayAPIClient:
            CollaborationAPIClient:
