// Copyright 2018-2022 CERN
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// In applying this license, CERN does not waive the privileges and immunities
// granted to it by virtue of its status as an Intergovernmental Organization
// or submit itself to any jurisdiction.

// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IDResolver is an autogenerated mock type for the IDResolver type
type IDResolver struct {
	mock.Mock
}

type IDResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *IDResolver) EXPECT() *IDResolver_Expecter {
	return &IDResolver_Expecter{mock: &_m.Mock}
}

// IDsForPath provides a mock function with given fields: ctx, path
func (_m *IDResolver) IDsForPath(ctx context.Context, path string) (string, string, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for IDsForPath")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, path)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IDResolver_IDsForPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IDsForPath'
type IDResolver_IDsForPath_Call struct {
	*mock.Call
}

// IDsForPath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *IDResolver_Expecter) IDsForPath(ctx interface{}, path interface{}) *IDResolver_IDsForPath_Call {
	return &IDResolver_IDsForPath_Call{Call: _e.mock.On("IDsForPath", ctx, path)}
}

func (_c *IDResolver_IDsForPath_Call) Run(run func(ctx context.Context, path string)) *IDResolver_IDsForPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IDResolver_IDsForPath_Call) Return(spaceID string, nodeID string, err error) *IDResolver_IDsForPath_Call {
	_c.Call.Return(spaceID, nodeID, err)
	return _c
}

func (_c *IDResolver_IDsForPath_Call) RunAndReturn(run func(context.Context, string) (string, string, error)) *IDResolver_IDsForPath_Call {
	_c.Call.Return(run)
	return _c
}

// NewIDResolver creates a new instance of IDResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDResolver {
	mock := &IDResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
