---
variables:
  - &golang_image 'docker.io/golang:1.24'

when:
  - event: [ push , manual ]
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [ pull_request ]

workspace:
  base: /go # use the go home dir as workspace to share go packages, see https://woodpecker-ci.org/docs/usage/workflow-syntax#workspace

steps:
  generate:
    image: *golang_image
    commands:
      - make go-generate
      - git diff --exit-code
  lint:
    image: *golang_image
    commands:
      - make lint
  build:
    image: *golang_image
    commands:
      - make build-ci
  #test:
  #  image: *golang_image
  #  depends_on: [ build ]
  #  commands:
  #    - apt-get update -qq && apt-get install -y inotify-tools 
  #    - make test
  #test-integration:
  #  image: *golang_image
  #  depends_on: [ build ]
  #  commands:
  #    - cd tests/integration && go test -race ./...
  #test-benchmark:
  #  image: *golang_image
  #  depends_on: [ build ]
  #  commands:
  #    - make test-benchmark
  upload:
    image: minio/mc:RELEASE.2021-10-07T04-19-58Z
    depends_on: [ build ]
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: cache_s3_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: cache_s3_secret_key
      S3_BUCKET:
        from_secret: cache_s3_bucket
      S3_ENDPOINT:
        from_secret: cache_s3_server
    commands:
      - mc alias set s3 $S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
      - mc cp -a --attr="content-type=application/octet-stream" $CI_WORKSPACE/cmd/revad/revad s3/$S3_BUCKET/opencloud-eu/reva/$CI_COMMIT_SHA-$CI_PIPELINE_NUMBER-revad
