---
variables:
  - &golang_image 'docker.io/golang:1.24'
  - &environment
    HTTP_PROXY:
      from_secret: ci_http_proxy
    HTTPS_PROXY:
      from_secret: ci_http_proxy

when:
  - event: [ push , manual ]
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [ pull_request ]
    path:
      exclude: [ 'README.md', '.woodpecker/*.yaml' ]

workspace:
  base: /go # use the go home dir as workspace to share go packages, see https://woodpecker-ci.org/docs/usage/workflow-syntax#workspace

steps:
  generate:
    image: *golang_image
    environment: *environment
    commands:
      - make go-generate
      - git diff --exit-code
  lint:
    image: *golang_image
    environment: *environment
    commands:
      - make lint
  build:
    image: *golang_image
    environment: *environment
    commands:
      - make build-ci
