---
depends_on: [test, test-integration]

variables:
  - &minio_image 'minio/mc:RELEASE.2021-10-07T04-19-58Z'
  - &s3_plugin_image 'plugins/s3-cache:1'

when:
  - event: [ push , manual ]
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [ pull_request ]

skip_clone: true
steps:
  purge:
    image: *minio_image
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: cache_s3_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: cache_s3_secret_key
      S3_BUCKET:
        from_secret: cache_s3_bucket
      S3_ENDPOINT:
        from_secret: cache_s3_server
    commands:
      - mc alias set s3 $S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
      - mc rm --recursive --force s3/$S3_BUCKET/opencloud-eu/reva
      - mc ls --recursive s3/$S3_BUCKET/opencloud-eu/reva