---
variables:
  - &s3_cache_image 'plugins/s3-cache:1'

when:
  - event: [ push , manual ]
    branch: stable-2.29
  - event: [ pull_request ]

skip_clone: true
steps:
  purge:
    image: *s3_cache_image
    settings:
      access_key:
        from_secret: cache_s3_access_key
      endpoint:
        from_secret: 
      flush: true
      flush_age: 1
      flush_path: dev/opencloud-eu/reva/
      secret_key:
        from_secret: cache_s3_secret_key
