---
variables:
  - &s3_cache_image 'plugins/s3-cache:1'

when:
  - event: [ push , manual ]
    branch: stable-2.29
  - event: [ pull_request ]

skip_clone: true
steps:
  purge:
    image: *s3_cache_image
    settings:
      access_key:
        from_secret: cache_s3_access_key
      endpoint: "https://s3.ci.opencloud.eu"
      flush: true
      flush_age: 1
      flush_path: dev/opencloud-eu/reva/
      secret_key:
        from_secret: cache_s3_secret_key
      S3_BUCKET:
        from_secret: cache_s3_bucket
      S3_ENDPOINT: "https://s3.ci.opencloud.eu"
    commands:
      - mc alias set s3 $S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
      - mc rm --recursive --force s3/$S3_BUCKET/${CI_REPO}/$CI_COMMIT_SHA-$CI_PIPELINE_NUMBER-revad
      - mc ls --recursive s3/$S3_BUCKET/opencloud-eu/reva
