---
depends_on: [ build ]

variables:
  - &golang_image 'docker.io/golang:1.24'

when:
  - event: [ push , manual ]
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [ pull_request ]

workspace:
  base: /go # use the go home dir as workspace to share go packages, see https://woodpecker-ci.org/docs/usage/workflow-syntax#workspace

steps:
  test-integration:
    image: *golang_image
    commands:
      - make test-integration
