---
depends_on: [ build ]

variables:
  - &golang_image 'docker.io/golang:1.24'

when:
  - event: [ push , manual ]
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [ pull_request, cron ]

workspace:
  base: /go # use the go home dir as workspace to share go packages, see https://woodpecker-ci.org/docs/usage/workflow-syntax#workspace

steps:
  fetch-binary:
    image: minio/mc:RELEASE.2021-10-07T04-19-58Z
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: cache_s3_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: cache_s3_secret_key
      S3_BUCKET:
        from_secret: cache_s3_bucket
      S3_ENDPOINT: "https://s3.ci.opencloud.eu"
    commands:
      - mc alias set s3 $S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
      - mc cp -a s3/$S3_BUCKET/opencloud-eu/reva/$CI_COMMIT_SHA-$CI_PIPELINE_NUMBER-revad $CI_WORKSPACE/cmd/revad/revad
  test-integration:
    image: *golang_image
    environment:
      HTTP_PROXY:
        from_secret: ci_http_proxy
      HTTPS_PROXY:
        from_secret: ci_http_proxy
    commands:
      # `make test-integration` rebuilds the binaries, which is unnecessary in the pipeline, so only using `go test` here
      - cd tests/integration && go test -race ./...
