---
variables:
  - &golang_image 'docker.io/golang:1.24'

when:
  - event: [ push , manual ]
    branch: stable-2.29
  - event: [ pull_request ]

workspace:
  base: /go # use the go home dir as workspace to share go packages, see https://woodpecker-ci.org/docs/usage/workflow-syntax#workspace

steps:
  test:
    image: *golang_image
    environment:
      HTTP_PROXY:
        from_secret: ci_http_proxy
      HTTPS_PROXY:
        from_secret: ci_http_proxy
    commands:
      - apt-get update -qq && apt-get install -y inotify-tools
      - make test
