---
variables:
  - &golang_image 'docker.io/golang:1.24'

when:
  - event: [ push, manual ]
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [ pull_request ]

steps:
  unit-test:
    image: *golang_image
    environment:
      HTTP_PROXY:
        from_secret: ci_http_proxy
      HTTPS_PROXY:
        from_secret: ci_http_proxy
    depends_on: [] # enable parallel steps
    commands:
      - make test